name: Build Poco F1 Docker Kernel
on:
  workflow_dispatch: # Allows manual trigger from the 'Actions' tab

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Builder
      uses: actions/checkout@v4

    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          # Change YOUR_USERNAME to your GitHub name
          kernel-url: https://github.com/YOUR_USERNAME/android_kernel_xiaomi_sdm845
          kernel-dir: beryllium_kernel
          kernel-branch: 16.0-bpf
          config: vendor/beryllium_defconfig
          arch: arm64
          
          # Clang r522817 is standard for Android 15/16-ready kernels
          aosp-clang: true
          aosp-clang-version: r522817
          android-version: 15
          
          # Optimizations
          disable-lto: false
          
          # Output format
          anykernel3: true
          
          # Root Access
          ksu: true
          ksu-version: main
