name: Build Poco F1 Docker Kernel
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Builder
      uses: actions/checkout@v4

    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          # Replace 'YOUR_USERNAME' with your GitHub username
          kernel-url: https://github.com/asif410/android_kernel_xiaomi_sdm845
          kernel-dir: kernel
          kernel-branch: 16.0-bpf
          config: vendor/beryllium_defconfig
          arch: arm64
          
          # Enable BOTH Clang and GCC (Required for SDM845)
          aosp-gcc: true
          aosp-clang: true
          
          # Use modern versions compatible with Android 16 ROMs
          android-version: 15
          aosp-clang-version: r522817
          
          # These flags help with Docker's BPF requirements
          disable-lto: false
          
          # Output and Root
          anykernel3: true
          ksu: true
          ksu-version: main
